services:
  watchbee:
    container_name: watchbee
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - watchbee_database
    restart: always
    env_file:
      - .env

  watchbee_database:
  
    image: postgres:18
    container_name: watchbee_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
