-- Lists table
CREATE TABLE IF NOT EXISTS Lists (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Media table
CREATE TABLE IF NOT EXISTS Media (
    id SERIAL PRIMARY KEY,
    tmdb_id INTEGER NOT NULL,
    type TEXT CHECK (type IN ('movie', 'show')),
    added_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    list_id INTEGER REFERENCES Lists(id) ON DELETE CASCADE
);

-- Default lists
INSERT INTO Lists (name) VALUES ('Watch'), ('Watched')
ON CONFLICT DO NOTHING;